FROM hklement/ubuntu-java
MAINTAINER Hauke Klement <dev@hklement.de>
RUN wget -O /tmp/jruby.tar.gz \
  https://s3.amazonaws.com/jruby.org/.../jruby-bin-1.7.17.tar.gz
RUN mkdir /usr/jruby
RUN tar xfz /tmp/jruby.tar.gz -C /usr/jruby
ENV PATH $PATH:/usr/jruby/jruby-1.7.17/bin
RUN gem install bundler
